/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicentrale;
import dialog.chooseServer;
import network.*;
import MyVariousUtils.*;
import java.awt.event.WindowEvent;
import propertiesHandler.*;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Nohch
 */
public class AppliCentrale extends javax.swing.JFrame {

    private NetworkBasicServer server;
    private LinkedList<commande> listeCommande;
    private commande currentCommande;
    private DefaultComboBoxModel model;
    
    /**
     * Creates new form AppliCentrale
     */
    public AppliCentrale() {
        //initComponents();
        this.setTitle("suis je ltraitre");
        
        new chooseServer(this,true).setVisible(true);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
       
    }
    public AppliCentrale(int param)
    {
        centraleProperties.load();
        if(param == 0)
        {   //pieces
            server = new NetworkBasicServer(Integer.parseInt(centraleProperties.getProp().getProperty("portPieces")),MessEntrantCBox);
            initMyComponents(param);
        }
        else if(param == 1)
        {   //lubrifiant
            server = new NetworkBasicServer(Integer.parseInt(centraleProperties.getProp().getProperty("portPneus")),MessEntrantCBox);
            initMyComponents(param);
        }
        else
        {   //pneus
            server = new NetworkBasicServer(Integer.parseInt(centraleProperties.getProp().getProperty("portLubrifiant")),MessEntrantCBox);
            initMyComponents(param);
        }

    }
    
    public void initMyComponents(int param)
    {
        initComponents();
        model = new DefaultComboBoxModel();
        if(param == 0)
        {
            this.setTitle("Centrale d'achat - PIECES");
            labelParametre.setText("PIECES");
        }
        else if (param == 1)
        {
            this.setTitle("Centrale d'achat - PNEUS");
            labelParametre.setText("PNEUS");
        }
        else
        {
            this.setTitle("Centrale d'achat - LUBRIFIANT");
            labelParametre.setText("LUBRIFIANT");
        }

    }
    
    public void parseRequest(String request)
    {//String priorite, String libelle, String type, int quantite
        String[] tokens = request.split("###");
        for(int i = 0; i < tokens.length;i++)
            System.out.println(tokens[i]);
        currentCommande = new commande(tokens[0],tokens[1],tokens[2],Integer.parseInt(tokens[3]));
        model.addElement(currentCommande.getLibelle());
        ComboBoxCommEnCours.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MessEntrantCBox = new javax.swing.JCheckBox();
        btnLireMess = new javax.swing.JButton();
        ComboBoxCommEnCours = new javax.swing.JComboBox();
        messageLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnVerifDisp = new javax.swing.JButton();
        radioBtnDisp = new javax.swing.JRadioButton();
        radioBtnNonDisp = new javax.swing.JRadioButton();
        btnEnvoyerReponse = new javax.swing.JButton();
        labelParametre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MessEntrantCBox.setText("Message Entrant");

        btnLireMess.setText("Lire Message");
        btnLireMess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLireMessActionPerformed(evt);
            }
        });

        messageLabel.setText(">>");
        messageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Details de la commande");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Caractéristiques", "Valeur"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnVerifDisp.setText("Verification disponibilité");
        btnVerifDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifDispActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBtnDisp);
        radioBtnDisp.setText("disponible");

        buttonGroup1.add(radioBtnNonDisp);
        radioBtnNonDisp.setText("non disponible");

        btnEnvoyerReponse.setText("Envoyer réponse");
        btnEnvoyerReponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvoyerReponseActionPerformed(evt);
            }
        });

        labelParametre.setBackground(new java.awt.Color(255, 255, 102));
        labelParametre.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        labelParametre.setForeground(new java.awt.Color(255, 102, 102));
        labelParametre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelParametre.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnVerifDisp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioBtnDisp)
                .addGap(66, 66, 66)
                .addComponent(radioBtnNonDisp)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(MessEntrantCBox))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLireMess, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComboBoxCommEnCours, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addComponent(labelParametre, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel2)
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btnEnvoyerReponse, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(labelParametre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(MessEntrantCBox)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLireMess)
                            .addComponent(ComboBoxCommEnCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEnvoyerReponse))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioBtnNonDisp)
                            .addComponent(radioBtnDisp)
                            .addComponent(btnVerifDisp))
                        .addGap(51, 51, 51))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerifDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifDispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerifDispActionPerformed

    private void btnEnvoyerReponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvoyerReponseActionPerformed
        String reponse = new String();
        if(radioBtnDisp.isSelected() || radioBtnNonDisp.isSelected() )
        {
            if(radioBtnNonDisp.isSelected())
                reponse += "Commande indisponible";
            else
                reponse += "Commande disponible";
            
            server.sendMessage(reponse);
        }
        else 
            JOptionPane.showMessageDialog(null, "Cocher la disponibilité!!!!!!!!!!!!!!!!!!!!");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnvoyerReponseActionPerformed

    private void btnLireMessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLireMessActionPerformed
        // TODO add your handling code here:
        parseRequest(server.getMessage());
        messageLabel.setText(">>" +currentCommande.toString());
        //listeCommande.add(new commande(String priorite, String libelle, String type, int quantite));
    }//GEN-LAST:event_btnLireMessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppliCentrale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppliCentrale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppliCentrale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppliCentrale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppliCentrale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxCommEnCours;
    private javax.swing.JCheckBox MessEntrantCBox;
    private javax.swing.JButton btnEnvoyerReponse;
    private javax.swing.JButton btnLireMess;
    private javax.swing.JButton btnVerifDisp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelParametre;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JRadioButton radioBtnDisp;
    private javax.swing.JRadioButton radioBtnNonDisp;
    // End of variables declaration//GEN-END:variables
}
