/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;
import MyVariousUtils.FichierLog;
import Serializer.BinarySerializer;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import people.*;
import Serializer.propertiesGarage;
import containers.containerUser;

/**
 *
 * @author Nohch
 */
public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        buttonMemPer = new javax.swing.JRadioButton();
        buttonExtHab = new javax.swing.JRadioButton();
        buttonOk = new javax.swing.JButton();
        passwordTxt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        usernameTxt.setText("nohcho");

        buttonGroup1.add(buttonMemPer);
        buttonMemPer.setText("Membre personnel");

        buttonGroup1.add(buttonExtHab);
        buttonExtHab.setText("Extérieur habilité");

        buttonOk.setText("OK");
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        passwordTxt.setText("abc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .addComponent(passwordTxt)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonMemPer)
                                .addGap(32, 32, 32)
                                .addComponent(buttonExtHab))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMemPer)
                    .addComponent(buttonExtHab))
                .addGap(18, 18, 18)
                .addComponent(buttonOk, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        // TODO add your handling code here:
        TechnicienExterieur tech = null;
        Mecanicien mecano = null;
        if(buttonMemPer.isSelected())   // si membre personnel, alors on instancie un mécano et essaie de le log
        {
            
            mecano = new Mecanicien();    
            mecano.setUsername(usernameTxt.getText().trim());
            propertiesGarage.load(0);
        }
        else if (buttonExtHab.isSelected())
        {
            tech = new TechnicienExterieur();
            tech.setUsername(usernameTxt.getText().trim());
            propertiesGarage.load(1);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Selectionnez un rôle!");
        }
        
        if(buttonMemPer.isSelected() ||  buttonExtHab.isSelected())
        {
            String value = propertiesGarage.getProp().getProperty(usernameTxt.getText());
            if(value == null)
            {
                JOptionPane.showMessageDialog(null,"User pas trouvé!");
            }
            else if(!value.equals(passwordTxt.getText()))
            {
                JOptionPane.showMessageDialog(null,"mot de passe incorrect!");
            }else
            {
                
                if(buttonMemPer.isSelected())
                {
                    if(mecano != null)
                        mecano.setMatricule(Integer.parseInt(propertiesGarage.getProp().getProperty(usernameTxt.getText() + "Id")));
                    try
                    {
                        BinarySerializer.serializeUser(new containerUser(false,mecano));
                    }
                    catch(Exception ex)
                    {
                        FichierLog fLog = new FichierLog("log/logsGarage");
                        fLog.writeLine("Erreur lors de serialisation de user ::"+ex.getMessage());
                    }
                    new atelierWindow(0).setVisible(true);
                }
                else
                {
                    if(tech != null)
                        tech.setMatricule(Integer.parseInt(propertiesGarage.getProp().getProperty(usernameTxt.getText() + "Id")));
                    try
                    {
                        BinarySerializer.serializeUser(new containerUser(true,tech));
                    }
                    catch(Exception ex)
                    {
                        FichierLog fLog = new FichierLog("log/logsGarage");
                        fLog.writeLine("Erreur lors de serialisation de user ::"+ex.getMessage());
                    }
                    new atelierWindow(1).setVisible(true);
                }
                dispose();     
            }
        }   
    }//GEN-LAST:event_buttonOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton buttonExtHab;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton buttonMemPer;
    private javax.swing.JButton buttonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
